DROP DATABASE IF EXISTS vk;
CREATE DATABASE vk;
SHOW DATABASES;
USE vk;
CREATE TABLE users (
	id INT  UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FIRST_NAME VARCHAR (50) NOT NULL,
	LAST_NAME VARCHAR (50) NOT NULL,
	EMAIL VARCHAR (100) NOT NULL UNIQUE,
	PHONE_NUMBER VARCHAR (12) NOT NULL UNIQUE,
	created_at DATETIME DEFAULT NOW(),
	updated_at DATETIME DEFAULT NOW()
);

CREATE TABLE profiles (
	user_id INT  UNSIGNED NOT NULL PRIMARY KEY,
	sex CHAR (1) NOT NULL,
	birthday DATE,
	hometown VARCHAR (100),
	photo_id INT UNSIGNED NOT NULL	
);




